# Generated by Django 4.2.6 on 2023-10-19 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="owner",
        ),
    ]
