# Generated by Django 4.2.6 on 2023-10-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="snippet",
            old_name="linenos",
            new_name="usable",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="style",
        ),
        migrations.AlterField(
            model_name="snippet",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("java", "Java"),
                    ("cpp", "C++"),
                    ("csharp", "C#"),
                ],
                default="python",
                max_length=100,
            ),
        ),
    ]
